insert into Course values 
('HIST876', 'Nephrology', 'HIST'),
('CS179', 'Arabic Language and Culture', 'CS'),
('RELI577', 'General Engineering', 'RELI'),
('GLOB335', 'Nursing', 'GLOB'),
('OPTO530', 'Gender Studies', 'OPTO'),
('BIOC494', 'History', 'BIOC'),
('INTA574', 'Engineering Management', 'INTA'),
('EED253', 'Ophthalmology', 'EED'),
('ARCH526', 'Computing and Mathematics', 'ARCH'),
('KINE255', 'Biomedical Science', 'KINE'),
('BME746', 'Physical Medicine and Rehabilitation', 'BME'),
('SEX116', 'Nursing', 'SEX'),
('JEWI601', 'Epidemiology and Public Health', 'JEWI'),
('SOFT884', 'Diagnostic Radiology', 'SOFT'),
('SI208', 'Computer Engineering', 'SI'),
('EART795', 'Software Design', 'EART'),
('PLAN764', 'Law', 'PLAN'),
('POLS712', 'Chinese', 'POLS'),
('NANE070', 'Mathematics and Engineering', 'NANE'),
('BIOL775', 'Diagnostic Radiology', 'BIOL'),
('EED213', 'Biochemistry', 'EED'),
('LANG605', 'Chemical Engineering', 'LANG'),
('FINE118', 'Diagnostic Radiology', 'FINE'),
('MED888', 'Chinese', 'MED'),
('FINE885', 'Biology and Mathematics', 'FINE'),
('ARCH732', 'Arts Co-op', 'ARCH'),
('GEO370', 'Applied Sustainability', 'GEO'),
('MUSI385', 'Human and Molecular Genetics', 'MUSI'),
('STAT048', 'Commerce', 'STAT'),
('SDS661', 'International Business', 'SDS'),
('CHE234', 'Anesthesiology', 'CHE'),
('MATH312', 'Economics', 'MATH'),
('GERM467', 'Engineering Chemistry', 'GERM'),
('RECR817', 'Immunology', 'RECR'),
('ERS729', 'Public Health', 'ERS'),
('CHE866', 'Latin American Studies', 'CHE'),
('LANG980', 'Public Administration', 'LANG'),
('CHE325', 'Gender Studies', 'CHE'),
('SOWO369', 'Biochemistry', 'SOWO'),
('OPTO426', 'Complex Project Leadership', 'OPTO'),
('SOWO680', 'Indigenous Studies', 'SOWO'),
('PLAN487', 'Mechanical and Materials Engineering', 'PLAN'),
('COMB117', 'Diagnostic Radiology', 'COMB'),
('SE870', 'Neurology', 'SE'),
('OPTO322', 'English as a Second Language', 'OPTO'),
('MATH550', 'English as a Second Language', 'MATH'),
('FINE741', 'Information Technology', 'FINE'),
('ANTH564', 'Italian Language and Culture', 'ANTH'),
('WOME705', 'Common Law', 'WOME'),
('ECE543', 'Cultural Studies', 'ECE'),
('ERS769', 'Art Conservation', 'ERS'),
('SOWO861', 'Physics', 'SOWO'),
('C&O458', 'Conflict Studies and Human Rights', 'C&O'),
('CULT610', 'Political and Legal Thought', 'CULT'),
('MED088', 'Orthopaedic Pathology', 'MED'),
('LEGA960', 'Neurology', 'LEGA'),
('OPTO552', 'Social Sciences - Co-op', 'OPTO'),
('GEO334', 'Womens Studies', 'GEO'),
('LANG809', 'Biomedical Engineering', 'LANG'),
('LEGA400', 'Computing and Mathematics', 'LEGA'),
('PHYS478', 'Biomedical Computing', 'PHYS'),
('FRCH872', 'French as a Second Language', 'FRCH'),
('CHE725', 'Mathematics and Statistics', 'CHE'),
('MED806', 'Public Administration', 'MED'),
('FRCH591', 'English Language and Literature', 'FRCH'),
('LANG830', 'Arts Co-op', 'LANG'),
('BME811', 'Computer Engineering', 'BME'),
('ERS626', 'Information Studies', 'ERS'),
('PUHE020', 'German Language and Culture', 'PUHE'),
('ACC431', 'Pathology and Experimental Medicine', 'ACC'),
('CS253', 'Engineering Co-op', 'CS'),
('MATH718', 'Nursing', 'MATH'),
('AVIA820', 'Biotechnology', 'AVIA'),
('ITAL449', 'Medical Oncology', 'ITAL'),
('SEX909', 'Bilingualism Studies', 'SEX'),
('BIOC523', 'Media Studies', 'BIOC'),
('SOWO364', 'Hematology', 'SOWO'),
('SOWO240', 'Nursing', 'SOWO'),
('CLAS069', 'Urology', 'CLAS'),
('KINE979', 'Obstetrics and Gynaecology', 'KINE'),
('SPAN895', 'Family Medicine: Global Health', 'SPAN'),
('NANE515', 'Palliative Care Medicine', 'NANE'),
('WOME547', 'Film and Media', 'WOME'),
('RELI402', 'Finance', 'RELI'),
('SYDE698', 'Finance', 'SYDE'),
('GLOB052', 'International Studies', 'GLOB'),
('EED282', 'International Studies', 'EED'),
('LANG612', 'Global Development Studies', 'LANG'),
('THEO384', 'Education', 'THEO'),
('PEAC583', 'Concurrent Education', 'PEAC'),
('JEWI528', 'Medicine', 'JEWI'),
('MUSI414', 'German Language and Culture', 'MUSI'),
('ANTH309', 'Biochemistry', 'ANTH'),
('SPAN080', 'Urology', 'SPAN'),
('EAS393', 'Electrical Engineering', 'EAS'),
('ECE506', 'Environmental Chemistry', 'ECE'),
('ERS346', 'Family Medicine: Anesthesia', 'ERS'),
('ACC318', 'Biomedical Computing', 'ACC'),
('SPAN428', 'Ophthalmic Medical Technology', 'SPAN'),
('PHYS515', 'Spanish', 'PHYS'),
('HIST805', 'World Literatures and Cultures', 'HIST'),
('BIOC465', 'Bilingualism Studies', 'BIOC'),
('HIST566', 'Arabic Language and Culture', 'HIST'),
('LEGA240', 'Music Theatre', 'LEGA'),
('CHEM020', 'Public Administration', 'CHEM'),
('ECON289', 'Information Technology', 'ECON'),
('PHIL214', 'Family Medicine: Indigenous Health', 'PHIL'),
('ENG03', 'Family Medicine: Intellectual and Developmental Disabilities', 'ENG'),
('INTA839', 'Nutrition', 'INTA'),
('CHEM206', 'Italian Language and Culture', 'CHEM'),
('SEX333', 'Education', 'SEX'),
('MSCI410', 'Academic Writing', 'MSCI'),
('MATH321', 'Gerontology', 'MATH'),
('CULT813', 'Healthcare Quality', 'CULT'),
('MED890', 'Modern Languages', 'MED'),
('FRCH760', 'Urban and Regional Planning', 'FRCH'),
('NANE707', 'Biotechnology', 'NANE'),
('LEGA158', 'Complex Project Leadership', 'LEGA'),
('C&O328', 'Classical Studies', 'C&O'),
('CULT974', 'Political Studies', 'CULT'),
('BME224', 'Biomedical Science', 'BME'),
('PSYC447', 'Biomedical Computing', 'PSYC'),
('BIOC785', 'Italian Language and Culture', 'BIOC'),
('PLAN513', 'Academic Writing', 'PLAN'),
('MATH668', 'Internal Medicine (Core Program)', 'MATH'),
('PSYC016', 'Systems Science', 'PSYC'),
('SOFT192', 'Cultural Studies', 'SOFT'),
('GEO672', 'Professional Inquiry', 'GEO'),
('RECR903', 'Mathematics and Engineering', 'RECR'),
('SDS366', 'Chinese', 'SDS'),
('PHYS654', 'Environmental Science', 'PHYS'),
('THEO382', 'Chinese', 'THEO'),
('LEGA310', 'Environmental Engineering', 'LEGA'),
('SEX990', 'Masters Thesis', 'SEX'),
('MUSI478', 'Environmental Geology', 'MUSI'),
('BIOL199', 'Environmental Toxicology', 'BIOL'),
('PSYC060', 'Physiotherapy', 'PSYC'),
('SOFT973', 'French as a Second Language', 'SOFT'),
('THEO098', 'Entrepreneurship and Innovation', 'THEO'),
('MATH126', 'GeoEngineering', 'MATH'),
('PHIL237', 'German Language and Culture', 'PHIL'),
('PHIL804', 'Computer Engineering', 'PHIL'),
('ACC932', 'Biostatistics', 'ACC'),
('SPAN291', 'Academic Writing', 'SPAN'),
('JEWI486', 'Film and Media', 'JEWI'),
('JEWI405', 'Anatomy and Physiology', 'JEWI'),
('KINE375', 'General Internal Medicine', 'KINE'),
('PUHE858', 'Health Studies', 'PUHE'),
('ARCH113', 'Medical Oncology', 'ARCH'),
('ACC999', 'Stage and Screen Studies', 'ACC'),
('ECE203', 'Mathematics and Engineering', 'ECE'),
('C&O371', 'Family Medicine', 'C&O'),
('SYDE419', 'Biomedical Engineering', 'SYDE'),
('PHYS141', 'Cultural Studies', 'PHYS'),
('PUHE202', 'Business Administration (MBA)', 'PUHE'),
('CLAS227', 'Aging and Health', 'CLAS'),
('HIST282', 'Software Design', 'HIST'),
('RELI801', 'Anatomical Sciences', 'RELI'),
('SDS395', 'Polish', 'SDS'),
('PLAN362', 'Biology', 'PLAN'),
('ITAL207', 'Engineering Chemistry', 'ITAL'),
('MEC591', 'Arts Co-op', 'MEC'),
('CLAS038', 'Ophthalmology', 'CLAS'),
('ENVK372', 'Medicine', 'ENVK'),
('GEO934', 'Indigenous Studies', 'GEO'),
('EAS440', 'Public Administration and Law combined', 'EAS'),
('NANE757', 'Anatomy and Physiology', 'NANE'),
('EART943', 'Biochemistry', 'EART'),
('CS853', 'Nephrology', 'CS'),
('MED349', 'Urology', 'MED'),
('CLAS560', 'Human and Molecular Genetics', 'CLAS'),
('EAS769', 'Environmental Life Sciences', 'EAS'),
('PUHE019', 'Social Performance Mgmt in the Extractive Industries', 'PUHE'),
('STAT436', 'Arts Management', 'STAT'),
('STAT433', 'General Surgery', 'STAT'),
('ECE548', 'Classics', 'ECE'),
('COMM594', 'Family Medicine', 'COMM'),
('SI465', 'Biology', 'SI'),
('BIOC316', 'Global Development Studies', 'BIOC'),
('ENVK844', 'Communication', 'ENVK'),
('SPAN202', 'Urology', 'SPAN'),
('ENG121', 'Family Medicine', 'ENG'),
('ERS931', 'Biomedical and Molecular Sciences', 'ERS'),
('COMM876', 'Commerce', 'COMM'),
('PEAC608', 'Academic Writing', 'PEAC'),
('SDS392', 'Civil Engineering', 'SDS'),
('INTA814', 'Environmental Geology', 'INTA'),
('PHIL275', 'Mining Engineering', 'PHIL'),
('CULT206', 'Engineering Chemistry', 'CULT'),
('EART628', 'Arts Leadership', 'EART'),
('BIOC279', 'Cultural Studies', 'BIOC'),
('SI371', 'German Language and Culture', 'SI'),
('GLOB235', 'Computer Science', 'GLOB'),
('BIOL884', 'Combined Medicine / Research', 'BIOL'),
('PHIL234', 'Gastroenteritis', 'PHIL'),
('WOME574', 'Population Health Risk Assessment and Management', 'WOME'),
('CLAS416', 'Orthopaedic Surgery', 'CLAS'),
('ERS959', 'Chemistry', 'ERS'),
('PHYS619', 'Family Medicine: Global Health', 'PHYS'),
('PHYS714', 'Entrepreneurship and Innovation', 'PHYS'),
('CULT941', 'Pre-internship Program', 'CULT'),
('SDS770', 'Law (Certificate)', 'SDS'),
('INTA086', 'Science (General)', 'INTA'),
('SPAN669', 'Mining Engineering', 'SPAN'),
('INTA751', 'Environmental Geology', 'INTA'),
('ECON359', 'Biochemistry', 'ECON'),
('ECON782', 'Political and Legal Thought', 'ECON'),
('GLOB753', 'Mathematics', 'GLOB'),
('PHYS606', 'Physics', 'PHYS'),
('MED105', 'Medicine', 'MED'),
('OPTO570', 'Social Sciences - Co-op', 'OPTO'),
('MSCI539', 'Chemistry', 'MSCI'),
('MEC182', 'Film Studies', 'MEC'),
('DESI606', 'Employment Relations', 'DESI'),
('ERS327', 'Rehabilitation Sciences', 'ERS'),
('ECE035', 'Computer Science', 'ECE'),
('RECR297', 'Pre-internship Program', 'RECR'),
('SDS890', 'Occupational Therapy', 'SDS'),
('SPAN270', 'Pathology and Experimental Medicine', 'SPAN'),
('MATH955', 'Education', 'MATH'),
('DESI348', 'Academic Writing', 'DESI'),
('COMB483', 'Environmental Sustainability', 'COMB'),
('MEC03', 'Anesthesiology', 'MEC'),
('JEWI999', 'Respirology', 'JEWI'),
('PEAC366', 'Software Design', 'PEAC'),
('PHIL395', 'French Studies', 'PHIL'),
('SPAN464', 'Data Science', 'SPAN'),
('EAS908', 'Neurology', 'EAS'),
('ENG989', 'Combined Medicine / Research', 'ENG'),
('INTA239', 'Lettres françaises', 'INTA'),
('EAS907', 'Indigenous Studies', 'EAS'),
('THEO070', 'Accounting', 'THEO'),
('MSCI128', 'Languages, Literatures and Cultures', 'MSCI'),
('CEE021', 'Pathology and Experimental Medicine', 'CEE'),
('INTA600', 'Media Studies', 'INTA'),
('COMM018', 'Pathology and Molecular Medicine', 'COMM'),
('OPTO523', 'Drama', 'OPTO'),
('GLOB531', 'Urban and Regional Planning', 'GLOB'),
('JEWI694', 'Management Analytics', 'JEWI'),
('ANTH938', 'Modern Languages', 'ANTH'),
('POLS211', 'Urology', 'POLS'),
('STAT790', 'Human Kinetics', 'STAT'),
('POLS428', 'Linguistics', 'POLS'),
('OPTO264', 'Health Administration', 'OPTO'),
('GLOB940', 'Arts Co-op', 'GLOB'),
('FRCH778', 'Management', 'FRCH'),
('MSCI392', 'Palliative Care Medicine', 'MSCI'),
('PUHE026', 'Music', 'PUHE'),
('DESI676', 'Anatomic Pathology', 'DESI'),
('PUHE172', 'Management in Artificial Intelligence', 'PUHE'),
('ACC633', 'Biology and Mathematics', 'ACC'),
('ERS786', 'Indigenous Languages', 'ERS'),
('SEX641', 'Internal Medicine (Core Program)', 'SEX'),
('MED153', 'Anesthesiology', 'MED'),
('WOME991', 'Anesthesiology', 'WOME'),
('BIOC626', 'Administration', 'BIOC'),
('SYDE939', 'Electronic Business', 'SYDE'),
('PLAN350', 'Epidemiology and Public Health', 'PLAN'),
('FINE482', 'Anthropology', 'FINE'),
('MATH297', 'Political Science', 'MATH'),
('ITAL286', 'Civil Engineering', 'ITAL'),
('ENVK284', 'General Surgery', 'ENVK'),
('ECE299', 'Accounting', 'ECE'),
('BIOC693', 'Canadian Studies', 'BIOC'),
('ANTH598', 'Law', 'ANTH'),
('PSYC844', 'Political and Legal Thought', 'PSYC'),
('PHIL321', 'Biochemistry', 'PHIL'),
('PUHE109', 'Rheumatology', 'PUHE'),
('MUSI133', 'Biochemistry', 'MUSI'),
('PHAR538', 'Family Medicine: Anesthesia', 'PHAR'),
('COMM399', 'Sociology', 'COMM'),
('RECR445', 'Pre-internship Program', 'RECR'),
('GERM689', 'Rheumatology', 'GERM'),
('MEC106', 'Anesthesiology', 'MEC'),
('SOWO505', 'Family Medicine: Rural Skills', 'SOWO'),
('SOFT549', 'Philosophy', 'SOFT'),
('ITAL075', 'Neurology', 'ITAL'),
('GEO952', 'Commerce', 'GEO'),
('MATH841', 'Mathematics and Engineering', 'MATH'),
('PSYC737', 'Executive MBA', 'PSYC'),
('ITAL834', 'Anesthesiology', 'ITAL'),
('CLAS624', 'Polish', 'CLAS'),
('ITAL882', 'International Development and Globalization', 'ITAL'),
('FINE674', 'Common Law', 'FINE'),
('SI949', 'Sexual and Gender Diversity', 'SI'),
('CHE679', 'Public Administration and Law combined', 'CHE'),
('MEC797', 'Cognitive Science', 'MEC'),
('EAS251', 'French as a Second Language', 'EAS'),
('SOWO149', 'Professional Inquiry', 'SOWO'),
('ECON451', 'Bilingualism Studies', 'ECON'),
('ANTH017', 'Geography', 'ANTH'),
('PHIL576', 'Elective Courses in Medicine', 'PHIL'),
('OPTO638', 'History', 'OPTO'),
('PHIL346', 'Geographic Information Science', 'PHIL'),
('PHIL708', 'Interprofessional Health Care Practice', 'PHIL'),
('SDS633', 'Occupational Therapy', 'SDS'),
('JEWI491', 'Bilingualism Studies', 'JEWI'),
('OPTO776', 'Orthopaedic Surgery', 'OPTO'),
('PHAR837', 'Family Medicine', 'PHAR'),
('GEO387', 'Mathematics', 'GEO'),
('MEC565', 'Gastroenterology', 'MEC'),
('CS734', 'Biomedical Computing', 'CS'),
('BME873', 'Environmental Chemistry', 'BME'),
('SOWO340', 'Population Health Risk Assessment and Management', 'SOWO'),
('ANTH905', 'Commerce and Law combined', 'ANTH'),
('ENVK927', 'Health Systems', 'ENVK'),
('CULT049', 'Arabic Language and Culture', 'CULT'),
('C&O676', 'Complex Project Leadership', 'C&O'),
('NANE282', 'Political and Legal Thought', 'NANE'),
('CS588', 'Occupational Therapy', 'CS'),
('SOWO945', 'Sociology', 'SOWO'),
('EART539', 'Immunology', 'EART'),
('BME462', 'Pediatrics', 'BME'),
('BME745', 'Biochemistry', 'BME'),
('LANG775', 'Mathematics', 'LANG'),
('OPTO346', 'Political Science', 'OPTO'),
('ARCH770', 'Environmental Geography (Earth Systems Sciences)', 'ARCH'),
('SPAN579', 'Philosophy', 'SPAN'),
('MSCI532', 'Classical Studies', 'MSCI'),
('ARCH467', 'Elective Courses in Medicine', 'ARCH'),
('PLAN958', 'Environmental Studies', 'PLAN'),
('SPAN372', 'Portuguese', 'SPAN'),
('ENVK375', 'Geographic Information Science', 'ENVK'),
('AVIA968', 'Mathematics and Statistics', 'AVIA'),
('SPAN784', 'Rehabilitation Science', 'SPAN'),
('PHAR373', 'Russian Language and Culture', 'PHAR'),
('ENG513', 'Communication', 'ENG'),
('C&O972', 'Mechanical and Materials Engineering', 'C&O'),
('BME620', 'Family Medicine', 'BME'),
('MATH992', 'Modern Languages', 'MATH'),
('PLAN027', 'Religious Studies', 'PLAN'),
('BME629', 'Finance', 'BME'),
('COMM966', 'Music Theatre', 'COMM'),
('ECE096', 'Biochemistry', 'ECE'),
('ECE730', 'Pathology and Molecular Medicine', 'ECE'),
('GEO295', 'Academic Writing', 'GEO'),
('PHAR653', 'Drama', 'PHAR'),
('PHYS986', 'Mining Engineering', 'PHYS'),
('STAT246', 'Family Medicine: Rural Skills', 'STAT'),
('ANTH827', 'Critical Care', 'ANTH'),
('ITAL220', 'Arts Leadership', 'ITAL'),
('THEO431', 'Urology', 'THEO'),
('ANTH965', 'Urology', 'ANTH'),
('GEO156', 'Critical Care', 'GEO'),
('RECR732', 'Health Systems', 'RECR'),
('BIOC968', 'Political and Legal Thought', 'BIOC'),
('CHEM654', 'Medieval Studies', 'CHEM'),
('EART824', 'Family Medicine: Anesthesia', 'EART'),
('LEGA799', 'Anthropology', 'LEGA'),
('GEO965', 'Family Medicine', 'GEO'),
('GEO515', 'Ophthalmic Medical Technology', 'GEO'),
('CULT082', 'Anthropology', 'CULT'),
('LANG397', 'Conflict Studies and Human Rights', 'LANG'),
('AVIA308', 'Risk Policy and Regulation', 'AVIA'),
('DESI016', 'Music', 'DESI'),
('ERS814', 'Pathology and Experimental Medicine', 'ERS'),
('SOWO887', 'Geology', 'SOWO'),
('EED992', 'Computer Science', 'EED'),
('MSCI728', 'Entrepreneurship and Innovation', 'MSCI'),
('CHE452', 'Public Health', 'CHE'),
('CS869', 'Nursing', 'CS'),
('MUSI361', 'Pre-internship Program', 'MUSI'),
('ECE494', 'Electrical Engineering', 'ECE'),
('SOWO153', 'Hematology', 'SOWO'),
('CHEM507', 'Information Technology', 'CHEM'),
('DESI718', 'Environmental Biology', 'DESI'),
('SDS350', 'Francophone Studies', 'SDS'),
('WOME844', 'Mathematical Physics', 'WOME'),
('ARCH303', 'Translational and Molecular Medicine', 'ARCH'),
('MUSI090', 'Management in Artificial Intelligence', 'MUSI'),
('SPAN642', 'Mathematics and Statistics', 'SPAN'),
('CHEM380', 'Cultural Studies', 'CHEM'),
('PLAN727', 'Civil Law', 'PLAN'),
('AVIA544', 'Law', 'AVIA'),
('MUSI575', 'Anesthesiology', 'MUSI'),
('SOFT070', 'Neurology', 'SOFT'),
('GEO195', 'Medicine', 'GEO'),
('BIOC742', 'Music', 'BIOC'),
('PEAC499', 'Urology', 'PEAC'),
('CULT651', 'Critical Care', 'CULT'),
('ECON400', 'Anesthesiology', 'ECON'),
('MSCI807', 'Music Theatre', 'MSCI'),
('NANE923', 'Chinese', 'NANE'),
('LEGA175', 'Drama', 'LEGA'),
('SI758', 'Biostatistics', 'SI'),
('GERM780', 'Law', 'GERM'),
('ERS893', 'Biostatistics', 'ERS'),
('SEX239', 'Portuguese', 'SEX'),
('BME461', 'Human Kinetics', 'BME'),
('THEO985', 'Drama', 'THEO'),
('KINE595', 'Nutrition', 'KINE'),
('PHIL287', 'Political Studies', 'PHIL'),
('CS699', 'Visual Arts', 'CS'),
('CULT197', 'Neurology', 'CULT'),
('LANG274', 'Software Design', 'LANG'),
('LANG016', 'Geological Sciences', 'LANG'),
('THEO701', 'English Language and Literature', 'THEO'),
('HIST647', 'Biopharmaceutical Science', 'HIST'),
('GEO596', 'Chemical and Environmental Toxicology', 'GEO');