insert into Department
values 
('ARCH', 'Architecture ', 'Engineering'),
('BME', 'Biomedical Engineering', 'Engineering'),
('CHE', 'Chemical Engineering', 'Engineering'),
('CEE', 'Civil and Environmental Engineering', 'Engineering'),
('ECE', 'Electrical and Computer Engineering', 'Engineering'),
('MSCI', 'Management Sciences', 'Engineering'),
('MEC', 'Mechanical and Mechatronics Engineering', 'Engineering'),
('NANO', 'Nanotechnology Engineering', 'Engineering'),
('SOFT', 'Software Engineering', 'Engineering'),
('SYDE', 'Systems Design Engineering', 'Engineering'),
('COMB', 'Combinatorics and Optimization', 'Math'),
('CS', 'Computer Science', 'Math'),
('MATH', 'Pure Mathematics', 'Math'),
('SE', 'Software Engineering', 'Math'),
('STAT', 'Statistics and Actuarial Science', 'Math'),
('C&O', 'Combinatronics and Optimization', 'Math'),
('EED', 'Environment, Enterprise and Development ', 'Environmental'),
('ERS', 'Environment, Resources and Sustainability ', 'Environmental'),
('GEO', 'Geography and Environmental Management', 'Environmental'),
('ENVK', 'Knowledge Integration ', 'Environmental'),
('PLAN', 'Planning ', 'Environmental'),
('ACC', 'Accounting and Finance ', 'Arts'),
('ANTH', 'Anthropology', 'Arts'),
('LANG', 'Applied Language Studies', 'Arts'),
('CLAS', 'Classical Studies', 'Arts'),
('COMM', 'Communication Arts', 'Arts'),
('CULT', 'Culture & Language Studies', 'Arts'),
('EAS', 'East Asian Studies', 'Arts'),
('ECON', 'Economics', 'Arts'),
('ENG', 'English Language and Literature', 'Arts'),
('FINE', 'Fine Arts', 'Arts'),
('FRCH', 'French Studies', 'Arts'),
('GERM', 'Germanic and Slavic Studies', 'Arts'),
('GLOB', 'Global Business and Digital Arts', 'Arts'),
('HIST', 'History', 'Arts'),
('INTA', 'International Affairs Balsillie School of', 'Arts'),
('ITAL', 'Italian Studies', 'Arts'),
('JEWI', 'Jewish Studies', 'Arts'),
('MED', 'Medieval Studies', 'Arts'),
('MUSI', 'Music', 'Arts'),
('PEAC', 'Peace and Conflict Studies', 'Arts'),
('PHIL', 'Philosophy', 'Arts'),
('POLS', 'Political Science', 'Arts'),
('PSYC', 'Psychology', 'Arts'),
('RELI', 'Religious Studies', 'Arts'),
('SEX', 'Sexuality, Marriage and Family Studies', 'Arts'),
('SDS', 'Social Development Studies', 'Arts'),
('SOWO', 'Social Work ', 'Arts'),
('LEGA', 'Sociology and Legal Studies', 'Arts'),
('SPAN', 'Spanish and Latin American Studies', 'Arts'),
('DESI', 'Stratford School of Interaction Design and Bsnss', 'Arts'),
('SI', 'Studies in Islam', 'Arts'),
('THEO', 'Theological Studies', 'Arts'),
('WOME', 'Women Studies', 'Arts');
